import type { NextRequest } from 'next/server';
import { createHash, randomBytes } from 'crypto';

export function extractBearerToken(request: NextRequest): string | null {
  const auth = request.headers.get('authorization') || '';
  const match = auth.match(/^Bearer\s+(.+)$/i);
  return match ? match[1].trim() : null;
}

export function isStripeApiKeyFormat(apiKey: string | null): boolean {
  if (!apiKey) return false;
  // Stripe-style API keys generated by this app are 64-character hex strings.
  return /^[a-f0-9]{64}$/i.test(apiKey);
}

export function generateApiKey(): string {
  return randomBytes(32).toString('hex');
}

export function hashApiKey(apiKey: string): string {
  return createHash('sha256').update(apiKey).digest('hex');
}

export function maskApiKey(apiKey: string): string {
  if (apiKey.length <= 8) return '***';
  return `aom_${apiKey.slice(0, 4)}...${apiKey.slice(-4)}`;
}
