import { promises as fs } from 'fs';
import path from 'path';
import { NextResponse } from 'next/server';

const HOST = 'https://alloemmanuals.com';
const PUBLIC_DIR = path.join(process.cwd(), 'public');

/**
 * Hard-coded route-based sitemaps generated by Next.js sitemap.ts routes.
 * These are not static files in /public, so they must be listed explicitly.
 */
const ROUTE_SITEMAPS = [
  `${HOST}/sitemap.xml`,
  `${HOST}/codes/sitemap.xml`,
  `${HOST}/community/sitemap.xml`,
  `${HOST}/maintenance/sitemap.xml`,
  `${HOST}/manual/sitemap.xml`,
  `${HOST}/vehicles/sitemap.xml`,
];

/**
 * Optional static sitemap files that may live in /public. They are listed
 * when present so the index never references a missing resource.
 */
const OPTIONAL_STATIC_SITEMAPS = [
  `${HOST}/bing-supplemental-sitemap.xml`,
];

async function collectUrlsetSitemaps(dir: string, baseDir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const results: string[] = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relativePath = path.relative(baseDir, fullPath);

    if (entry.isDirectory()) {
      const nested = await collectUrlsetSitemaps(fullPath, baseDir);
      results.push(...nested);
      continue;
    }

    if (!entry.name.toLowerCase().endsWith('.xml')) continue;
    if (relativePath.toLowerCase() === 'sitemap_index.xml') continue;

    try {
      const head = await fs.readFile(fullPath, 'utf8').then((s) => s.slice(0, 200));
      if (head.includes('<urlset')) {
        results.push(`${HOST}/${relativePath.replace(/\\/g, '/')}`);
      }
    } catch {
      // ignore unreadable files
    }
  }

  return results;
}

async function existsInPublic(relativePath: string): Promise<boolean> {
  try {
    const stat = await fs.stat(path.join(PUBLIC_DIR, relativePath));
    return stat.isFile();
  } catch {
    return false;
  }
}

export async function GET() {
  const discovered = await collectUrlsetSitemaps(PUBLIC_DIR, PUBLIC_DIR);

  const optionalStatic = await Promise.all(
    OPTIONAL_STATIC_SITEMAPS.map(async (loc) => {
      const relative = new URL(loc).pathname.slice(1);
      return (await existsInPublic(relative)) ? loc : null;
    })
  );

  const sitemaps = Array.from(new Set([
    ...ROUTE_SITEMAPS,
    ...optionalStatic.filter(Boolean) as string[],
    ...discovered,
  ]));

  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemaps
    .map((loc) => `  <sitemap><loc>${loc}</loc><lastmod>${new Date().toISOString().split('T')[0]}</lastmod></sitemap>`)
    .join('\n')}\n</sitemapindex>`;

  return new NextResponse(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
