import type { Metadata } from 'next';
import Link from 'next/link';
import { COMPANY_INFO } from '@/lib/companyInfo';

export const metadata: Metadata = {
  title: 'Terms of Service | SpotOnAuto',
  description: 'Terms and conditions for using SpotOnAuto, including AI-generated content disclaimers, affiliate disclosures, liability limitations, and data usage policies.',
  alternates: { canonical: 'https://spotonauto.com/terms-of-service' },
};

export default function TermsOfService() {
  return (
    <main className="min-h-screen pt-24 pb-16">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 text-gray-300 space-y-8">
        <div>
          <h1 className="text-3xl font-display font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-500">Last updated: April 2, 2026</p>
        </div>

        <p>
          Welcome to SpotOnAuto, operated by Widescope Industries LLC (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), a Service-Disabled
          Veteran-Owned Small Business (SDVOSB). By accessing or using spotonauto.com (the &quot;Site&quot;), you agree to these
          Terms of Service. If you do not agree, please do not use the Site.
        </p>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-cyan-400">1. Description of Service</h2>
          <p className="text-sm">
            SpotOnAuto provides free AI-powered automotive repair guides, diagnostic trouble code (DTC) lookups, wiring
            diagrams, vehicle specifications, parts recommendations, and related tools. Our content is generated through
            a combination of:
          </p>
          <ul className="list-disc pl-6 space-y-1 text-sm">
            <li><strong>OEM corpus data</strong> — factory service manual information for vehicles from 1982–2025. Pages backed by this data display an &quot;OEM Verified&quot; badge.</li>
            <li><strong>AI-generated content</strong> — for vehicles outside our OEM corpus coverage (2026 and newer), content is generated by artificial intelligence (Google Gemini) and clearly labeled as AI-generated.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-cyan-400">2. Important Safety Disclaimer</h2>
          <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4 text-sm">
            <p className="text-red-300 font-semibold mb-2">Automotive repair involves inherent risks.</p>
            <ul className="list-disc pl-6 space-y-1 text-red-200/80">
              <li>All content on SpotOnAuto is for <strong>informational purposes only</strong> and does not replace professional mechanical advice.</li>
              <li>Always consult your vehicle&apos;s official service manual before performing any repair.</li>
              <li>You are solely responsible for your safety and the safety of others when performing vehicle repairs.</li>
              <li>SpotOnAuto, Widescope Industries LLC, and its operators are <strong>not liable</strong> for any damage, injury, or loss resulting from the use of information on this Site.</li>
              <li>If you are not confident in performing a repair, take your vehicle to a qualified mechanic.</li>
              <li><strong>We strongly recommend professional assistance for complex or safety-critical repairs.</strong></li>
            </ul>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-cyan-400">3. AI-Generated Content Disclaimer</h2>
          <p className="text-sm">
            Portions of this Site are generated by artificial intelligence. While we take steps to ensure accuracy —
            including grounding AI responses in factory service manual data when available — AI can make mistakes.
            AI-generated content may contain inaccuracies, omissions, or outdated information.
          </p>
          <p className="text-sm">
            <strong>We clearly distinguish between OEM-verified content and AI-generated content.</strong> Pages
            within our corpus coverage (1982–2025) display an &quot;OEM Verified&quot; badge when the underlying data
            comes from factory service manuals. All other content is labeled as AI-generated. We do not publish
            content for vehicle types where we have no data (e.g., electric vehicles without OEM coverage).
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-cyan-400">4. Affiliate Relationships &amp; Advertising</h2>
          <p className="text-sm">
            SpotOnAuto earns revenue through affiliate commissions and advertising. When you click on certain product
            links and make a purchase, we may earn a commission at no additional cost to you. Our affiliate partnerships include:
          </p>
          <ul className="list-disc pl-6 space-y-1 text-sm">
            <li><strong>Amazon Associates</strong> — we earn commissions on qualifying purchases made through our Amazon links.</li>
            <li><strong>TOPDON</strong> — we earn a 5% commission on TOPDON diagnostic tool and battery tester purchases made through our referral links.</li>
          </ul>
          <p className="text-sm">
            We also display advertisements through Google AdSense. For complete details, see our{' '}
            <Link href="/disclosure" className="text-cyan-400 hover:underline">Affiliate Disclosure</Link>.
          </p>
          <p className="text-sm">
            <strong>Affiliate relationships do not influence our content.</strong> Repair guides, diagnostic results, and
            vehicle specifications are generated based on OEM data and diagnostic accuracy, not affiliate commissions.
            Product recommendations are based on relevance to the user&apos;s diagnostic context.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-cyan-400">5. Intellectual Property</h2>
          <p className="text-sm">
            The Site&apos;s design, code, AI-generated text, tools, and original content are the property of Widescope
            Industries LLC. Factory service manual data is used under applicable research and reference provisions.
            Vehicle manufacturer names, model names, and trademarks are the property of their respective owners and
            are used for identification purposes only. SpotOnAuto is not affiliated with or endorsed by any vehicle manufacturer.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-cyan-400">6. User Accounts</h2>
          <p className="text-sm">
            If you create an account, you are responsible for maintaining the security of your login credentials.
            You may delete your account and all associated data at any time by emailing support@spotonauto.com.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-cyan-400">7. Limitation of Liability</h2>
          <p className="text-sm">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, SPOTONAUTO AND WIDESCOPE INDUSTRIES LLC SHALL NOT BE LIABLE FOR
            ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO
            PERSONAL INJURY, PROPERTY DAMAGE, OR LOSS OF PROFITS, ARISING FROM YOUR USE OF THE SITE OR RELIANCE
            ON ANY CONTENT PROVIDED HEREIN. OUR TOTAL LIABILITY SHALL NOT EXCEED $100.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-cyan-400">8. Modifications</h2>
          <p className="text-sm">
            We reserve the right to modify these Terms at any time. Changes will be posted on this page with an
            updated date. Continued use of the Site after changes constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-cyan-400">9. Governing Law</h2>
          <p className="text-sm">
            These Terms are governed by the laws of the State of Texas, without regard to conflict of law principles.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-cyan-400">10. Contact</h2>
          <p className="text-sm">
            Questions about these Terms? Contact us at:<br />
            <strong>{COMPANY_INFO.legalName}</strong><br />
            {COMPANY_INFO.streetAddress}<br />
            {COMPANY_INFO.city}, {COMPANY_INFO.state} {COMPANY_INFO.zip}<br />
            Phone: <a href={COMPANY_INFO.phoneTel} className="text-cyan-400 hover:underline">{COMPANY_INFO.phoneDisplay}</a><br />
            Email: <a href={`mailto:${COMPANY_INFO.supportEmail}`} className="text-cyan-400 hover:underline">{COMPANY_INFO.supportEmail}</a><br />
            Business hours: {COMPANY_INFO.businessHours}
          </p>
        </section>
      </div>
    </main>
  );
}
